GRANT CONNECT TO WIKJ;
GRANT RESOURCE TO WIKJ;
ALTER USER WIKJ quota unlimited on SYSTEM;

CREATE TABLE WIKJ."T_WIKJ_HAB_PRUEBAFINAL"(
	id Number(5) NOT NULL PRIMARY KEY,
	nuip Number(10)NOT NULL UNIQUE,
	full_name VARCHAR(50),
	phone VARCHAR(15),
	address VARCHAR(30)
)

DROP TABLE WIKJ."T_WIKJ_HAB_PRUEBAFINAL";

SELECT * FROM WIKJ.T_WIKJ_HAB_PRUEBAFINAL twh;

INSERT INTO WIKJ.T_WIKJ_HAB_PRUEBAFINAL (id,nuip,full_name,phone,address) VALUES (:id,:nuip,:full_name,:phone,:address);
SELECT HAB.id, HAB.nuip, HAB.full_name,HAB.phone,HAB.address FROM WIKJ.T_WIKJ_HAB_PRUEBAFINAL HAB WHERE HAB.id = :id;
